### PR TITLE
Fix inconsistent mindx (-> c_h) for multilevel MHD simulations

### LINKED ISSUE #135: Multilevel artifact
For the INCITE runs (and also by @mfournier01 at smaller scale), some multi level artifacts started to show up recently:

image

image

This is data directly extracted from the output files (so it's not a plotting issue).

Interestingly, whatever happens at the boundaries does not grow/extend fast, e.g., it takes several thousands of cycles to show up and even after several thousand more cycles it's still contained to only a few cells width.

The issue can reliably be reproduced when restarting a specific INCITE sim (with binary probably corresponding to 3ce0a88) from last year with a current binary.

Data being read and immediately written does not show the artifact indicating that both reading and writing data is not the cause of the issue.
I also tried to go back to the 1D limited prolongation (versus the current 3D limited one), but this didn't change anything.
Also given that it does not show up for the old version, using cons for prolongation/restriction should also not be the root cause.

I have not been able to reliably reproduce on smaller scales/different pgen.
So next debugging steps could be 
- [ ] smaller reproducer with same physics
- [ ] then/or reduce/limit pgen/physics
- [ ] bisect between current and `3ce0a88`

### PR DESCRIPTION
**Pull request by pgrete**
Fixes #135 

`mindx` was reduced across ranks, but the reduced value was not used in the following c_h calculation resulting in inconsistent `c_h` depending on the distribution of blocks.
A reproducer input (can be run on a laptop) is below and I'll create a regression test for this in the very near future.

Also bumps Kokkos to 4.5.1 (to support AMD APUs).

Reproducer:

- works fine on 1, 2, and 4 ranks but crashes after 3 cycles on 8 or 16 ranks,

```
# AthenaPK - a performance portable block structured AMR MHD code
# Copyright (c) 2020, Athena Parthenon Collaboration. All rights reserved.
# Licensed under the BSD 3-Clause License (the "LICENSE");

<comment>
problem = 3D Hydro linear wave convergence

<job>
problem_id = linear_wave_mhd

<problem/linear_wave>
compute_error = true  # when 'true' outputs L1 error compared to initial data
wave_flag = 0         # Wave family number (0 - 4 for adiabatic hydro)
amp       = 1.0e-6    # Wave Amplitude
vflow     = 0.0       # background flow velocity
test      = true

<parthenon/mesh>
refinement  = static
nghost = 2

nx1        = 64        # Number of zones in X1-direction
x1min      =-0.2     # minimum value of X1
x1max      = 0.2     # maximum value of X1
ix1_bc     = periodic        # inner-X1 boundary flag
ox1_bc     = periodic        # outer-X1 boundary flag

nx2        = 64        # Number of zones in X2-direction
x2min      =-0.2     # minimum value of X2
x2max      = 0.2     # maximum value of X2
ix2_bc     = periodic        # inner-X2 boundary flag
ox2_bc     = periodic        # outer-X2 boundary flag

nx3        = 64        # Number of zones in X3-direction
x3min      =-0.2     # minimum value of X3
x3max      = 0.2     # maximum value of X3
ix3_bc     = periodic        # inner-X3 boundary flag
ox3_bc     = periodic        # outer-X3 boundary flag

<parthenon/meshblock>
nx1        = 16        # Number of zones in X1-direction
nx2        = 16        # Number of zones in X2-direction
nx3        = 16        # Number of zones in X3-direction

<parthenon/static_refinement6>
x1min = -0.01 
x1max =  0.01
x2min = -0.01
x2max =  0.01
x3min = -0.01
x3max =  0.01
level =  4


<parthenon/time>
integrator = rk2
cfl = 0.3
tlim = 1.0
nlim = 3
perf_cycle_offset = 2 # number of inital cycles not to be included in perf calc

<hydro>
fluid = glmmhd
eos = adiabatic
riemann = hlld
reconstruction = plm
gamma = 1.666666666666667 # gamma = C_p/C_v
scratch_level = 0 # 0 is actual scratch (tiny); 1 is HBM

<parthenon/output0>
file_type = rst
dt = 0.01
variables = cons
```

### CODE REVIEW

**Review by mfournier01 — APPROVED** [review]

File: src/hydro/hydro.cpp [hunk 1]
```diff
@@ -135,6 +135,7 @@ void PreStepMeshUserWorkInLoop(Mesh *pmesh, ParameterInput *pin, SimTime &tm) {
     // Finally update c_h
     const auto &cfl_hyp = hydro_pkg->Param<Real>("cfl");
     const auto &dt_hyp = hydro_pkg->Param<Real>("dt_hyp");
+    mindx = hydro_pkg->Param<Real>("mindx");
```
Comment (BenWibking) [inline src/hydro/hydro.cpp:138]: Maybe this variable could be renamed? That would have avoided the original bug.

**Review by BenWibking — COMMENTED** [review]
Minor comment.

File: src/hydro/hydro.cpp (hunk 1 above)
Comment (pgrete) [reply src/hydro/hydro.cpp:138]: This logic should eventually be moved to function that's only triggered on mesh refinement (as only then mindx changes).
I'll update it then if that's okay.
